language: python
python:
    - "2.7"
# command to install dependencies
install:
    - pip install -r requirements.txt
# command to run tests
script:
    - cd webapp/webapp/static
    - npm install
    - cd ../../
    - ./manage.py test app/tests
    - cd ../
    - python scripts/run_tests.py
